<?php

namespace AppBundle\Repository;

/**
 * CoverSongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoverSongRepository extends \Doctrine\ORM\EntityRepository
{
}
